// AUTO-GENERATED by design-system/build.mjs from design-system/tokens.json — DO NOT EDIT.
// To change the BhojPe brand color, edit BHOJPE_PRIMARY in tokens.json and re-run the build.

export const BHOJPE_PRIMARY = "#FA5252"

export const palette = {
  "blue": {
    "50": "#E7F5FF",
    "400": "#4DABF7",
    "500": "#228BE6",
    "600": "#1971C2"
  },
  "mint": {
    "50": "#E6FCF5",
    "500": "#12B886",
    "600": "#0CA678"
  },
  "green": {
    "50": "#E9F7EF",
    "500": "#2FB344",
    "700": "#2B8A3E"
  },
  "orange": {
    "50": "#FFF4D6",
    "500": "#F59F00",
    "700": "#E67700"
  },
  "red": {
    "50": "#FFF5F5",
    "500": "#FA5252",
    "700": "#E03131",
    "800": "#C92A2A"
  },
  "purple": {
    "50": "#F3F0FF",
    "500": "#845EF7",
    "700": "#7048E8"
  },
  "gray": {
    "0": "#FFFFFF",
    "50": "#F8F9FA",
    "100": "#F1F3F5",
    "200": "#E9ECEF",
    "300": "#DEE2E6",
    "400": "#CED4DA",
    "500": "#ADB5BD",
    "600": "#868E96",
    "700": "#495057",
    "900": "#212529",
    "1000": "#000000"
  }
}

export const light = {
  "brand": {
    "primary": "#FA5252",
    "hover": "#E14A4A",
    "pressed": "#CD4343",
    "soft": "#FFF3F3",
    "subtle": "#FEE0E0",
    "onPrimary": "#FFFFFF",
    "focusRing": "rgba(250, 82, 82, 0.28)"
  },
  "interactive": {
    "primary": "#228BE6",
    "hover": "#1971C2",
    "soft": "#E7F5FF",
    "onPrimary": "#FFFFFF"
  },
  "text": {
    "primary": "#212529",
    "secondary": "#495057",
    "muted": "#868E96",
    "disabled": "#ADB5BD",
    "inverse": "#FFFFFF",
    "link": "#228BE6"
  },
  "bg": {
    "canvas": "#F8F9FA",
    "surface": "#FFFFFF",
    "subtle": "#F1F3F5",
    "hover": "#F1F3F5",
    "overlay": "rgba(33, 37, 41, 0.55)"
  },
  "border": {
    "default": "#E9ECEF",
    "divider": "#DEE2E6",
    "control": "#ADB5BD",
    "strong": "#CED4DA"
  },
  "status": {
    "success": "#12B886",
    "successStrong": "#2FB344",
    "successText": "#2B8A3E",
    "successSoft": "#E9F7EF",
    "warning": "#F59F00",
    "warningText": "#E67700",
    "warningSoft": "#FFF4D6",
    "danger": "#FA5252",
    "dangerHover": "#E03131",
    "dangerText": "#E03131",
    "dangerSoft": "#FFF5F5",
    "info": "#4DABF7",
    "infoText": "#1971C2",
    "infoSoft": "#E7F5FF",
    "premium": "#845EF7",
    "premiumText": "#7048E8",
    "premiumSoft": "#F3F0FF",
    "teal": "#12B886",
    "tealSoft": "#E6FCF5",
    "neutral": "#868E96",
    "neutralSoft": "#F1F3F5"
  },
  "button": {
    "primaryBg": "#FA5252",
    "primaryHover": "#E14A4A",
    "primaryText": "#FFFFFF",
    "secondaryBg": "#FFFFFF",
    "secondaryBorder": "#E9ECEF",
    "secondaryText": "#212529",
    "outlineBorder": "#228BE6",
    "outlineText": "#228BE6",
    "outlineBg": "#FFFFFF"
  },
  "control": {
    "checkboxChecked": "#228BE6",
    "checkboxUnchecked": "#FFFFFF",
    "checkboxBorder": "#ADB5BD",
    "radioSelected": "#228BE6",
    "radioUnselected": "#FFFFFF",
    "radioBorder": "#ADB5BD",
    "toggleOn": "#12B886",
    "toggleOff": "#CED4DA",
    "tabActiveBg": "#E7F5FF",
    "tabActiveText": "#228BE6",
    "tabIndicator": "#228BE6",
    "menuSelectedBg": "#F1F3F5",
    "menuSelectedText": "#228BE6",
    "focusRing": "rgba(250, 82, 82, 0.28)"
  },
  "badge": {
    "successBg": "#E9F7EF",
    "successText": "#2B8A3E",
    "warningBg": "#FFF4D6",
    "warningText": "#E67700",
    "errorBg": "#FFF5F5",
    "errorText": "#E03131",
    "infoBg": "#E7F5FF",
    "infoText": "#1971C2",
    "premiumBg": "#F3F0FF",
    "premiumText": "#7048E8",
    "brandBg": "#FFF3F3",
    "brandText": "#E14A4A"
  },
  "table": {
    "availableBg": "#C8E6A0",
    "availableText": "#1F1F1F",
    "availableDot": "#22A559",
    "diningBg": "#FCE5A0",
    "diningText": "#1F1F1F",
    "diningDot": "#E0A800",
    "diningTimer": "#FF3131",
    "billingBg": "#A8D8F0",
    "billingText": "#1F1F1F",
    "billingDot": "#1E6BE0",
    "occupiedBg": "#FFB38E",
    "occupiedText": "#1F1F1F",
    "occupiedDot": "#E07A2E"
  },
  "kds": {
    "new": "#228BE6",
    "preparing": "#F59F00",
    "ready": "#2FB344",
    "delayed": "#FA5252",
    "completed": "#2FB344"
  },
  "order": {
    "pending": "#F59F00",
    "accepted": "#228BE6",
    "preparing": "#F59F00",
    "ready": "#2FB344",
    "completed": "#2FB344",
    "cancelled": "#FA5252",
    "rejected": "#FA5252",
    "delivery": "#12B886",
    "online": "#228BE6",
    "offline": "#868E96"
  },
  "room": {
    "available": "#2FB344",
    "occupied": "#228BE6",
    "housekeeping": "#F59F00",
    "maintenance": "#FA5252",
    "checkIn": "#228BE6",
    "checkOut": "#F59F00",
    "vacant": "#2FB344"
  },
  "food": {
    "veg": "#2FB344",
    "nonVeg": "#E03131"
  }
}

export const dark = {
  "brand": {
    "primary": "#FA5252",
    "hover": "#E14A4A",
    "pressed": "#CD4343",
    "soft": "rgba(250, 82, 82, 0.14)",
    "subtle": "rgba(250, 82, 82, 0.24)",
    "onPrimary": "#FFFFFF",
    "focusRing": "rgba(250, 82, 82, 0.28)"
  },
  "interactive": {
    "primary": "#4DABF7",
    "hover": "#228BE6",
    "soft": "rgba(77, 171, 247, 0.14)",
    "onPrimary": "#FFFFFF"
  },
  "text": {
    "primary": "#F1F3F5",
    "secondary": "#C1C7CD",
    "muted": "#8C959F",
    "disabled": "#5C6570",
    "inverse": "#212529",
    "link": "#4DABF7"
  },
  "bg": {
    "canvas": "#0F1115",
    "surface": "#1A1D23",
    "subtle": "#22262E",
    "hover": "#2A2F38",
    "overlay": "rgba(0, 0, 0, 0.65)"
  },
  "border": {
    "default": "#2C313A",
    "divider": "#343A44",
    "control": "#5C6570",
    "strong": "#444B55"
  },
  "status": {
    "success": "#12B886",
    "successStrong": "#2FB344",
    "successText": "#2B8A3E",
    "successSoft": "rgba(47, 179, 68, 0.14)",
    "warning": "#F59F00",
    "warningText": "#E67700",
    "warningSoft": "rgba(245, 159, 0, 0.14)",
    "danger": "#FA5252",
    "dangerHover": "#E03131",
    "dangerText": "#E03131",
    "dangerSoft": "rgba(250, 82, 82, 0.14)",
    "info": "#4DABF7",
    "infoText": "#1971C2",
    "infoSoft": "rgba(77, 171, 247, 0.14)",
    "premium": "#845EF7",
    "premiumText": "#7048E8",
    "premiumSoft": "rgba(132, 94, 247, 0.16)",
    "teal": "#12B886",
    "tealSoft": "rgba(18, 184, 134, 0.14)",
    "neutral": "#868E96",
    "neutralSoft": "#22262E"
  },
  "button": {
    "primaryBg": "#FA5252",
    "primaryHover": "#E14A4A",
    "primaryText": "#FFFFFF",
    "secondaryBg": "#1A1D23",
    "secondaryBorder": "#2C313A",
    "secondaryText": "#F1F3F5",
    "outlineBorder": "#228BE6",
    "outlineText": "#228BE6",
    "outlineBg": "#1A1D23"
  },
  "control": {
    "checkboxChecked": "#228BE6",
    "checkboxUnchecked": "#1A1D23",
    "checkboxBorder": "#ADB5BD",
    "radioSelected": "#228BE6",
    "radioUnselected": "#1A1D23",
    "radioBorder": "#ADB5BD",
    "toggleOn": "#12B886",
    "toggleOff": "#444B55",
    "tabActiveBg": "rgba(77, 171, 247, 0.14)",
    "tabActiveText": "#4DABF7",
    "tabIndicator": "#4DABF7",
    "menuSelectedBg": "#22262E",
    "menuSelectedText": "#4DABF7",
    "focusRing": "rgba(250, 82, 82, 0.28)"
  },
  "badge": {
    "successBg": "rgba(47, 179, 68, 0.14)",
    "successText": "#69DB7C",
    "warningBg": "rgba(245, 159, 0, 0.14)",
    "warningText": "#FFC078",
    "errorBg": "rgba(250, 82, 82, 0.14)",
    "errorText": "#FF8787",
    "infoBg": "rgba(77, 171, 247, 0.14)",
    "infoText": "#74C0FC",
    "premiumBg": "rgba(132, 94, 247, 0.16)",
    "premiumText": "#B197FC",
    "brandBg": "rgba(250, 82, 82, 0.14)",
    "brandText": "#FA5252"
  },
  "table": {
    "availableBg": "#C8E6A0",
    "availableText": "#1F1F1F",
    "availableDot": "#22A559",
    "diningBg": "#FCE5A0",
    "diningText": "#1F1F1F",
    "diningDot": "#E0A800",
    "diningTimer": "#FF3131",
    "billingBg": "#A8D8F0",
    "billingText": "#1F1F1F",
    "billingDot": "#1E6BE0",
    "occupiedBg": "#FFB38E",
    "occupiedText": "#1F1F1F",
    "occupiedDot": "#E07A2E"
  },
  "kds": {
    "new": "#228BE6",
    "preparing": "#F59F00",
    "ready": "#2FB344",
    "delayed": "#FA5252",
    "completed": "#2FB344"
  },
  "order": {
    "pending": "#F59F00",
    "accepted": "#228BE6",
    "preparing": "#F59F00",
    "ready": "#2FB344",
    "completed": "#2FB344",
    "cancelled": "#FA5252",
    "rejected": "#FA5252",
    "delivery": "#12B886",
    "online": "#228BE6",
    "offline": "#868E96"
  },
  "room": {
    "available": "#2FB344",
    "occupied": "#228BE6",
    "housekeeping": "#F59F00",
    "maintenance": "#FA5252",
    "checkIn": "#228BE6",
    "checkOut": "#F59F00",
    "vacant": "#2FB344"
  },
  "food": {
    "veg": "#2FB344",
    "nonVeg": "#E03131"
  }
}

export const typography = {
  "fontFamily": "Montserrat",
  "fontFamilyFallback": "-apple-system, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif",
  "size": {
    "xs": 11,
    "sm": 12,
    "md": 13,
    "base": 14,
    "lg": 16,
    "xl": 20,
    "xxl": 24,
    "display": 32
  },
  "weight": {
    "regular": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700,
    "heavy": 800
  }
}

export const spacing = {
  "xxs": 2,
  "xs": 4,
  "sm": 8,
  "md": 16,
  "lg": 24,
  "xl": 32,
  "xxl": 48
}

export const radius = {
  "none": 0,
  "xs": 2,
  "sm": 4,
  "md": 8,
  "lg": 12,
  "xl": 16,
  "pill": 9999
}

export const shadow = {
  "sm": "0 1px 2px rgba(33, 37, 41, 0.06)",
  "md": "0 4px 12px rgba(33, 37, 41, 0.08)",
  "lg": "0 12px 32px rgba(33, 37, 41, 0.12)"
}

// CSS-variable references (resolve at runtime, so they follow dark mode).
// Use these in inline styles / sx:  style={{ background: cssVar.brand.primary }}
// Use the plain `light` values only where a CSS var cannot work (SVG
// presentation attributes, canvas, chart libraries, print HTML strings).
export const cssVar = {
  "brand": {
    "primary": "var(--bp-brand-primary)",
    "hover": "var(--bp-brand-hover)",
    "pressed": "var(--bp-brand-pressed)",
    "soft": "var(--bp-brand-soft)",
    "subtle": "var(--bp-brand-subtle)",
    "onPrimary": "var(--bp-brand-on-primary)",
    "focusRing": "var(--bp-brand-focus-ring)"
  },
  "interactive": {
    "primary": "var(--bp-interactive-primary)",
    "hover": "var(--bp-interactive-hover)",
    "soft": "var(--bp-interactive-soft)",
    "onPrimary": "var(--bp-interactive-on-primary)"
  },
  "text": {
    "primary": "var(--bp-text-primary)",
    "secondary": "var(--bp-text-secondary)",
    "muted": "var(--bp-text-muted)",
    "disabled": "var(--bp-text-disabled)",
    "inverse": "var(--bp-text-inverse)",
    "link": "var(--bp-text-link)"
  },
  "bg": {
    "canvas": "var(--bp-bg-canvas)",
    "surface": "var(--bp-bg-surface)",
    "subtle": "var(--bp-bg-subtle)",
    "hover": "var(--bp-bg-hover)",
    "overlay": "var(--bp-bg-overlay)"
  },
  "border": {
    "default": "var(--bp-border-default)",
    "divider": "var(--bp-border-divider)",
    "control": "var(--bp-border-control)",
    "strong": "var(--bp-border-strong)"
  },
  "status": {
    "success": "var(--bp-status-success)",
    "successStrong": "var(--bp-status-success-strong)",
    "successText": "var(--bp-status-success-text)",
    "successSoft": "var(--bp-status-success-soft)",
    "warning": "var(--bp-status-warning)",
    "warningText": "var(--bp-status-warning-text)",
    "warningSoft": "var(--bp-status-warning-soft)",
    "danger": "var(--bp-status-danger)",
    "dangerHover": "var(--bp-status-danger-hover)",
    "dangerText": "var(--bp-status-danger-text)",
    "dangerSoft": "var(--bp-status-danger-soft)",
    "info": "var(--bp-status-info)",
    "infoText": "var(--bp-status-info-text)",
    "infoSoft": "var(--bp-status-info-soft)",
    "premium": "var(--bp-status-premium)",
    "premiumText": "var(--bp-status-premium-text)",
    "premiumSoft": "var(--bp-status-premium-soft)",
    "teal": "var(--bp-status-teal)",
    "tealSoft": "var(--bp-status-teal-soft)",
    "neutral": "var(--bp-status-neutral)",
    "neutralSoft": "var(--bp-status-neutral-soft)"
  },
  "button": {
    "primaryBg": "var(--bp-button-primary-bg)",
    "primaryHover": "var(--bp-button-primary-hover)",
    "primaryText": "var(--bp-button-primary-text)",
    "secondaryBg": "var(--bp-button-secondary-bg)",
    "secondaryBorder": "var(--bp-button-secondary-border)",
    "secondaryText": "var(--bp-button-secondary-text)",
    "outlineBorder": "var(--bp-button-outline-border)",
    "outlineText": "var(--bp-button-outline-text)",
    "outlineBg": "var(--bp-button-outline-bg)"
  },
  "control": {
    "checkboxChecked": "var(--bp-control-checkbox-checked)",
    "checkboxUnchecked": "var(--bp-control-checkbox-unchecked)",
    "checkboxBorder": "var(--bp-control-checkbox-border)",
    "radioSelected": "var(--bp-control-radio-selected)",
    "radioUnselected": "var(--bp-control-radio-unselected)",
    "radioBorder": "var(--bp-control-radio-border)",
    "toggleOn": "var(--bp-control-toggle-on)",
    "toggleOff": "var(--bp-control-toggle-off)",
    "tabActiveBg": "var(--bp-control-tab-active-bg)",
    "tabActiveText": "var(--bp-control-tab-active-text)",
    "tabIndicator": "var(--bp-control-tab-indicator)",
    "menuSelectedBg": "var(--bp-control-menu-selected-bg)",
    "menuSelectedText": "var(--bp-control-menu-selected-text)",
    "focusRing": "var(--bp-control-focus-ring)"
  },
  "badge": {
    "successBg": "var(--bp-badge-success-bg)",
    "successText": "var(--bp-badge-success-text)",
    "warningBg": "var(--bp-badge-warning-bg)",
    "warningText": "var(--bp-badge-warning-text)",
    "errorBg": "var(--bp-badge-error-bg)",
    "errorText": "var(--bp-badge-error-text)",
    "infoBg": "var(--bp-badge-info-bg)",
    "infoText": "var(--bp-badge-info-text)",
    "premiumBg": "var(--bp-badge-premium-bg)",
    "premiumText": "var(--bp-badge-premium-text)",
    "brandBg": "var(--bp-badge-brand-bg)",
    "brandText": "var(--bp-badge-brand-text)"
  },
  "table": {
    "availableBg": "var(--bp-table-available-bg)",
    "availableText": "var(--bp-table-available-text)",
    "availableDot": "var(--bp-table-available-dot)",
    "diningBg": "var(--bp-table-dining-bg)",
    "diningText": "var(--bp-table-dining-text)",
    "diningDot": "var(--bp-table-dining-dot)",
    "diningTimer": "var(--bp-table-dining-timer)",
    "billingBg": "var(--bp-table-billing-bg)",
    "billingText": "var(--bp-table-billing-text)",
    "billingDot": "var(--bp-table-billing-dot)",
    "occupiedBg": "var(--bp-table-occupied-bg)",
    "occupiedText": "var(--bp-table-occupied-text)",
    "occupiedDot": "var(--bp-table-occupied-dot)"
  },
  "kds": {
    "new": "var(--bp-kds-new)",
    "preparing": "var(--bp-kds-preparing)",
    "ready": "var(--bp-kds-ready)",
    "delayed": "var(--bp-kds-delayed)",
    "completed": "var(--bp-kds-completed)"
  },
  "order": {
    "pending": "var(--bp-order-pending)",
    "accepted": "var(--bp-order-accepted)",
    "preparing": "var(--bp-order-preparing)",
    "ready": "var(--bp-order-ready)",
    "completed": "var(--bp-order-completed)",
    "cancelled": "var(--bp-order-cancelled)",
    "rejected": "var(--bp-order-rejected)",
    "delivery": "var(--bp-order-delivery)",
    "online": "var(--bp-order-online)",
    "offline": "var(--bp-order-offline)"
  },
  "room": {
    "available": "var(--bp-room-available)",
    "occupied": "var(--bp-room-occupied)",
    "housekeeping": "var(--bp-room-housekeeping)",
    "maintenance": "var(--bp-room-maintenance)",
    "checkIn": "var(--bp-room-check-in)",
    "checkOut": "var(--bp-room-check-out)",
    "vacant": "var(--bp-room-vacant)"
  },
  "food": {
    "veg": "var(--bp-food-veg)",
    "nonVeg": "var(--bp-food-non-veg)"
  }
}

export const bhojpeTokens = { BHOJPE_PRIMARY, palette, light, dark, typography, spacing, radius, shadow, cssVar }
export default bhojpeTokens
